spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:mensageria_db}
  username: ${DB_USER:postgres}
  password: ${DB_PASSWORD:postgres}
  jpa:
  hibernate:
  ddl-auto: update # desenvolvimento: cria/atualiza tabelas; em produção prefira
  open-in-view: false # evita queries lazy acidentais no meio da serialização JSON
  server:
    port: 8080